name: Commit Lint

on:
  workflow_call:

jobs:
  commit-lint:
    runs-on: ubuntu-latest
    steps:
      # Step to check out the code
      - name: Checkout Code
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        with:
          fetch-depth: 0

      # Step to set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.0.3
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      # Step to cache node modules
      - name: Cache node modules
        uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
        id: npm-cache
        with:
          path: ~/.npm
          key: npm-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            npm-${{ runner.os }}-

      # Step to install dependencies
      - name: Install dependencies
        run: npm ci

      # Step to run commitlint
      - name: Lint PR commits
        run: |
          # Validate all commits from the base and head
          BASE_SHA=${{ github.event.pull_request.base.sha }}
          HEAD_SHA=${{ github.sha }}

          COMMITS=$(git log $BASE_SHA..$HEAD_SHA --pretty=format:"%H")
          echo "Linting commits:"
          echo "$COMMITS"

          echo "$COMMITS" | while read COMMIT; do
            echo "Checking commit: $COMMIT"
            npx commitlint --from $COMMIT^ --to $COMMIT
          done
