name: Pre-commit Hooks Check

on:
  workflow_call:
    inputs:
      # Define the input parameters for the workflow
      encoded_modified_files:
        required: true
        type: string
        description: "The base64 encoded list of modified files to check"
      owner:
        required: true
        description: "Owner of the repository"
        type: string
      repositories:
        required: true
        description: "Comma-separated list of repositories to generate tokens for"
        type: string
    secrets:
      github_app_id:
        required: true
        description: "GitHub App ID for token generation"
      github_app_private_key:
        required: true
        description: "Private key for the GitHub App to generate a token"
    outputs:
      # Define the output parameters for the workflow
      main_outcome:
        description: "The status of the Pre-commit job"
        value: ${{ jobs.pre-commit-check.outputs.main_outcome }}

jobs:
  pre-commit-check:
    name: main
    runs-on: ubuntu-latest

    steps:
      # Step to generate GitHub App token
      - name: Generate GitHub App Token
        uses: actions/create-github-app-token@df432ceedc7162793a195dd1713ff69aefc7379e # v2.0.6
        id: app-token
        with:
          app-id: ${{ secrets.github_app_id }}
          private-key: ${{ secrets.github_app_private_key }}
          owner: ${{ inputs.owner }}
          repositories: ${{ inputs.repositories }}

      # Step to check out the code
      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.4.2
        with:
          submodules: recursive
          persist-credentials: false
          token: ${{ steps.app-token.outputs.token }}

      - name: Install dependencies
        run: |
          # Install necessary dependencies
          sudo apt-get update -y && \
          sudo apt-get install -y unzip direnv

      # Step to set up Python
      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: "3.13"

      - name: Install Pre-commit
        run: |
          # Install Pre-commit and other dependencies
          python -m pip install --upgrade pip
          pip install pre-commit shellcheck-py

      - name: Setup Repository
        run: |
          # Setup the repository
          SKIP=init_git_submodule ./bootstrap.sh # this script should be present in the caller repository and should run pre-commit install

          # Extract the updated PATH and write it to GITHUB_ENV
          NEW_PATH=$(direnv exec . bash -c 'echo $PATH')
          echo "PATH=$NEW_PATH" >> $GITHUB_ENV

      # Step to cache pre-commit environments
      - name: Cache pre-commit envs
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: |
            pre-commit-

      # Step to run Pre-commit Hooks only to files which have changed
      - name: Run Pre-commit
        id: main
        env:
          ENCODED_MODIFIED_FILES: ${{ inputs.encoded_modified_files }}
        run: |
          # Run pre-commit only on modified files
          echo "$ENCODED_MODIFIED_FILES" | base64 -d | xargs pre-commit run --files

    outputs:
      main_outcome: ${{ steps.main.outcome }}
