name: Pre-commit Hooks Check

on:
  workflow_call:

jobs:
  pre-commit-check:
    name: main
    runs-on: ubuntu-latest

    steps:
      # Step Check out the code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step to install necessary dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip direnv

      # Step Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      # Step Install Pre-commit
      - name: Install Pre-commit
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit shellcheck-py

      # Step to setup the repository
      - name: Setup Repository
        run: |
          ./bootstrap.sh # this script should be present in the caller repository and should run pre-commit install

          # Extract the updated PATH and write it to GITHUB_ENV
          NEW_PATH=$(direnv exec . bash -c 'echo $PATH')
          echo "PATH=$NEW_PATH" >> $GITHUB_ENV

      # Step to run Pre-commit Hooks only to files which have changed
      - name: Run Pre-commit
        run: |
          git fetch --depth=2 origin $(git rev-parse --abbrev-ref HEAD)
          MODIFIED_FILES=$(git diff --name-only HEAD^ HEAD)
          echo "$MODIFIED_FILES" | xargs pre-commit run --files
