name: Pre-commit Hooks Check

on:
  pull_request:
    branches:
      - main

jobs:
  github_list_pr_files:
    name: List Modified Files
    uses: ./.github/workflows/github-list-pr-files.yml
    with:
      github_repository: ${{ github.repository }}
      github_event_pull_request_number: ${{ github.event.pull_request.number }}
    secrets:
      github_secret_token: ${{ secrets.GITHUB_TOKEN }}

  pre-commit-check:
    name: Run Pre-commit Hooks
    needs:
      - github_list_pr_files
    uses: ./.github/workflows/pre-commit.yml
    with:
      encoded_modified_files: ${{ needs.github_list_pr_files.outputs.encoded_modified_files }}
