name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    uses: zcode-ia/gitops-workflows/.github/workflows/release.yml@e6190ca441f297c5b5ec3794726ed20d08fded1d # v1.12.0
    with:
      owner: ${{ github.repository_owner }}
      repositories: ${{ github.event.repository.name }}
    secrets:
      github_app_id: ${{ secrets.CREATE_TOKEN_APP_ID }}
      github_app_private_key: ${{ secrets.CREATE_TOKEN_APP_PRIVATE_KEY }}
