name: Terragrunt Set Environment

on:
  workflow_call:
    inputs:
      # Define the input parameters for the workflow
      github_base_ref:
        required: true
        type: string
        description: The base branch of the pull request.
    outputs:
      # Define the output parameters for the workflow
      working_dir:
        description: "The working directory based on the base branch"
        value: ${{ jobs.terragrunt_set_environment.outputs.working_dir }}

jobs:
  terragrunt_set_environment:
    name: main
    runs-on: ubuntu-latest
    steps:
      # Step to checkout the code
      - name: Checkout code
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

      - name: Set Environment
        id: set_env
        env:
          INPUT_GITHUB_BASE_REF: ${{ inputs.github_base_ref }}
        run: |
          # Determine the environment settings

          # Set the working directory based on the base branch
          if [[ "$INPUT_GITHUB_BASE_REF" == "main" ]]; then
            WORKING_DIR=live/prod
          else
            WORKING_DIR=live/$INPUT_GITHUB_BASE_REF
          fi
          echo "${WORKING_DIR}"
          echo "working_dir=${WORKING_DIR}" >> $GITHUB_OUTPUT
    outputs:
      working_dir: ${{ steps.set_env.outputs.working_dir }}
